//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// WeeklyPlanner.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_WEEKLYPLANNER_FORM          101
#define IDD_TAB1_VIEW                   102
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_WeeklyPlannerTYPE           130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_EDIT_MENU                   306
#define IDD_DDAY_ADD_DIALOG             316
#define IDD_DIALOG_PROFILE_MODIFY       318
#define IDB_BITMAP1                     320
#define IDC_BITMAP_PROFILE_DEFAULT      320
#define IDD_DIALOG_HISTORY              321
#define IDB_BITMAP_MAIN                 327
#define IDB_BITMAP_DDAY                 328
#define IDB_BITMAP_HISTORY              329
#define IDC_MESSAGE                     1001
#define IDC_BUTTON1                     1002
#define IDC_BUTTON2                     1003
#define IDC_BUTTON12                    1004
#define IDC_TODO_CHECKBOX1              1004
#define IDC_TODO_CHECKBOX2              1005
#define IDC_TODO_CHECKBOX3              1006
#define IDC_TODO_CHECKBOX4              1007
#define IDC_TODO_CHECKBOX5              1008
#define IDC_TODO_CHECKBOX6              1009
#define IDC_TODO_CHECKBOX7              1010
#define IDC_TODO_CHECKBOX8              1011
#define IDC_DDAY_DELETE_BUTTON          1012
#define IDC_ADD_TODO_START              1013
#define IDC_ADD_TODO_FINISH             1014
#define IDC_ADD_TODO_MEMO               1015
#define IDC_ADD_TODO_BUTTON             1016
#define IDC_TODO_ACHIVE_PROGRESS        1017
#define IDC_TODO_DELETE_BUTTON1         1018
#define IDC_TODO_DELETE_BUTTON2         1019
#define IDC_TODO_DELETE_BUTTON3         1020
#define IDC_TODO_DELETE_BUTTON5         1021
#define IDC_TODO_DELETE_BUTTON6         1022
#define IDC_TODO_DELETE_BUTTON7         1023
#define IDC_TODO_DELETE_BUTTON4         1024
#define IDC_DDAY_MODIFY_BUTTON          1025
#define IDC_TODO_DELETE_BUTTON8         1026
#define IDC_LIST1                       1037
#define IDC_PREV_SONG                   1041
#define IDC_NEXT_SONG                   1042
#define IDC_PAUSE_SONG                  1043
#define IDC_SONGS                       1044
#define IDC_PROFILE_PHOTO               1046
#define IDC_MESSAGE_MODIFY_BUTTON       1047
#define IDC_MUSIC_INFO                  1048
#define IDC_DDAY_LIST_CNTL              1049
#define IDC_DDAY_ADD_BUTTON             1050
#define IDC_DDAY_MEMO                   1051
#define IDC_DDAY_TITLE                  1052
#define IDC_NUM_OF_DDAY                 1053
#define IDC_TODO_TITLE2                 1053
#define IDC_DDAY_FINISH                 1054
#define IDC_WISE_SAYING                 1055
#define IDC_TODO_START                  1056
#define IDC_TODO_END                    1057
#define IDC_MONTHCALENDAR1              1057
#define IDC_EDIT_DDAY_TITLE             1058
#define IDC_EDIT_DDAY_MEMO              1059
#define IDC_BUTTON_MODIFY_CANCLE        1060
#define IDC_BUTTON_IMAGEFILE_OPEN       1061
#define IDC_BUTTON_MODIFY_APPLY         1062
#define IDC_PROFILE_MODAL               1064
#define IDC_BUTTON_PROFILE_OPEN         1065
#define IDC_BUTTON_PROFILE_DELETE       1066
#define IDC_PLAYLIST                    1067
#define IDC_BUTTON_SOUND_DELETE         1068
#define IDC_DATETIMEPICKER_HISTORY      1069
#define IDC_LIST_HISTORY                1070
#define IDC_PROGRESS_HISTORY            1071
#define IDC_BUTTON_HISTORY_OK           1072
#define IDC_STATIC_PERECENT             1073
#define IDC_STATIC_CHECK1               1074
#define IDC_STATIC_CHECK2               1075
#define IDC_STATIC_CHECK3               1076
#define IDC_STATIC_CHECK4               1077
#define IDC_STATIC_CHECK5               1078
#define IDC_STATIC_CHECK6               1079
#define IDC_STATIC_CHECK7               1080
#define IDC_STATIC_CHECK8               1081
#define IDC_TODO_TITLE                  1082
#define ID_32771                        32771
#define ID_HISTORY_VIEW                 32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
